[phases.setup]
nixPkgs = [
  "python312Full",
  "python312Packages.pip",
  "python312Packages.setuptools",
  "python312Packages.wheel",
  "gcc"
]

[phases.install]
cmds = [
  "python --version",
  "pip --version",
  "pip install -r requirements.txt"
]

[start]
cmd = "streamlit run main.py --server.port $PORT --server.address 0.0.0.0 --server.headless true"
