[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "streamlit run main.py --server.port $PORT --server.address 0.0.0.0 --server.headless true"
